### PR TITLE
Replace deprecated bindShared method with singleton for 5.2

### PR DESCRIPTION
**Pull request by ghost**
This replaces the deprecated bindShared() method for use with Laravel 5.2 and replaces with singleton()

### CODE REVIEW

**Comment by kiaking** [comment]
:+1:

**Comment by eduardostuart** [comment]
:+1:

**Comment by VernonGrant** [comment]
I just wanted to do this myself!  I spent hours trying to find out why composer wasn't updating haha

**Comment by ghost** [comment]
Can this please be merged! Literally just wasted an entire hour trying to figure this out....

**Comment by eduardostuart** [comment]
@taylorotwell

**Comment by mendrinos** [comment]
:+1:

**Comment by balping** [comment]
PLEASE!! I wasted 2 hours with this

**Comment by mirzabusatlic** [comment]
Please merge this :)

**Comment by ikselll** [comment]
:+1:

**Comment by JordanDalton** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
Please close this. This repo has been abandoned for over a year.

**Comment by spyric** [comment]
You can use https://laravelcollective.com/docs/5.2/html  .

**Comment by andrewault** [comment]
:+1: switched to https://laravelcollective.com/docs/5.2/html

**Comment by balping** [comment]
@spyric is right. I tried it and it works.

**Comment by mendrinos** [comment]
moved as well to laravelcollective - it looks like this package is discontinued but not announced it at all!

**Comment by GrahamCampbell** [comment]
> moved as well to laravelcollective - it looks like this package is discontinued but not announced it at all!

It was announced over a year ago.

**Pull request closed without merging**
