### PR TITLE
Bug on FromBuilder.php

### PR DESCRIPTION
**Pull request by pazzoone**
HOW TO REPRODUCE BUG:
I have an m:m relation in my isolated form.
This relation si rendered by a list of checkboxes.
Checkboxes names are in the form form_name[relation_name][]

BUG:
Form checkboxes autofill functionalities works well only when:
1. On new form (method=get)
2. On posting some errors

ERROR:
On edit form data the autofill functionalities wont' work because $posted is a Collection, so my edit.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This repo is not maintained, and is read only anyway.

**Comment by pazzoone** [comment]
where is new repo?

**Comment by GrahamCampbell** [comment]
There isn't one.

**Comment by pazzoone** [comment]
Thanks, i found the new project home [Laravel Collective](http://laravelcollective.com/) and the repo on [GitHub](https://github.com/LaravelCollective/html).

**Comment by GrahamCampbell** [comment]
> Thanks, i found the new project home

This isn't the "new project". This is just **a** community maintained package. Not official or associated with Laravel.

**Pull request closed without merging**
