### PR TITLE
Update HtmlBuilder.php

### PR DESCRIPTION
**Pull request by codermaiyu**

### CODE REVIEW

**Comment by driesvints** [comment]
Heya,

Thanks for your PR. You've submitted this on the Illuminate organization which is a read-only sub split of `laravel/framework`. Please submit your PR on the https://github.com/laravel/framework repository. 

Thanks!

**Comment by crynobone** [comment]
@driesvints can't we archive this repo?

**Comment by driesvints** [comment]
@crynobone the package is still available on packagist so it needs to stay available.

**Comment by crynobone** [comment]
@driesvints https://help.github.com/en/articles/archiving-repositories

Archiving a repository doesn't delete it, just turn it into read-only mode.

**Comment by crynobone** [comment]
Further reading on the topic: https://help.github.com/en/articles/about-archiving-repositories

**Comment by driesvints** [comment]
@crynobone thanks. I'll check this with Taylor.

**Pull request closed without merging**
