### PR TITLE
Update HtmlServiceProvider.php

### PR DESCRIPTION
**Pull request by hpakdaman**
BindShare was dipricarted and replaced with singleton in laravel 5.2

Please pull to 5.2 branch

### CODE REVIEW

**Comment by simonfranz** [comment]
This really should be merged for using the package with Laravel 5.2
@GrahamCampbell  is it possible to merge this pr for compatibility reason?

**Comment by GrahamCampbell** [comment]
No, please close this.

**Comment by GrahamCampbell** [comment]
This package has been deprecated and replaced for a very long time.

**Comment by hpakdaman** [comment]
َSO , what package we can use instead of this ?

**Comment by simonfranz** [comment]
I think this should be the replacement: https://laravelcollective.com/docs/5.2/html
edit: just confirming, you can just switch to the laravelcollective - at least it worked for me

**Comment by nicolaiskogheim** [comment]
If this repository is deprecated it really should have a README saying so.

**Comment by GrahamCampbell** [comment]
It's never accepted PRs anyway. This is clearly marked.

**Comment by nicolaiskogheim** [comment]
When did I say anything about PRs?

I said this repo should have a README file because, clearly, lots of newcomers have issues with it.
How one goes about adding one to this repository is not something I intend to investigate.

**Comment by GrahamCampbell** [comment]
This repo was never intended for use in this way. It is merely a subsplit. Use it to install components from the main framework, and that's it.

**Comment by GrahamCampbell** [comment]
This has been removed from the framework, and that's it.

**Comment by nicolaiskogheim** [comment]
Could we at least have a notice in the repository description? Since adding a README is a no-go

**Comment by GrahamCampbell** [comment]
This repo is read-only.

**Comment by GrahamCampbell** [comment]
That means nothing will ever be added here, ever.

**Comment by GrahamCampbell** [comment]
Including a readme.

**Comment by nicolaiskogheim** [comment]
I get the impression that you don't read what I write, so I guess this discussion is over.

**Comment by GrahamCampbell** [comment]
> Could we at least have a notice in the repository description?

We DO!

**Comment by nicolaiskogheim** [comment]
> [READ ONLY] Subtree split of the Illuminate HTML component (see laravel/framework)

You mean this one? If so, then no, we don't. It does not say anything about this repository being either deprecated or removed from the main framework.

It could for instance have said "Deprecated", and then people would understand that they should be looking elsewhere for this functionality. We could even point them to Collective/html, since that is what they should be using.

**Comment by GrahamCampbell** [comment]
It's read only, and not in the framework anymore, so the link is obvious. We're not going to recommend any third party over another. It's not an official replacement.

**Comment by vlakoff** [comment]
Just add a goddamn readme note so that people aren't confused. Refs #32.

**Comment by GrahamCampbell** [comment]
Nobody even has push access to this repo, so that's not possible.

**Comment by vlakoff** [comment]
You mean push access to the laravelcollective repo? I can understand you do not want to direct to a third-party package you have no control on.

So, at the goddamn very least, please add this goddamn readme note:

> The HTML component has been removed from the Laravel framework and is not maintained anymore.

**Comment by vlakoff** [comment]
You can also add to be extra clear:

> Pull requests won't be treated.

**Comment by jeffz2012** [comment]
Yupp, it is confusing ... and a time-waster because of that.

**Pull request closed without merging**
