### PR TITLE
Update trait name

### PR DESCRIPTION
**Pull request by v-jacob**
Update MacroableTrait to Macroable

### CODE REVIEW

**Comment by onbjerg** [comment]
:+1:

**Comment by 41eight** [comment]
@GrahamCampbell https://github.com/illuminate/support/commit/02cb2173a1f2e4b4afea96765eb51520e957632c

**Comment by GrahamCampbell** [comment]
Yeh, I know. I can't merge this pull.

**Comment by GrahamCampbell** [comment]
Only taylor has push access to the illuminate subsplits.

**Comment by 41eight** [comment]
Thanks @GrahamCampbell

**Comment by TimeToogo** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
I've let Taylor know about this. Though, the idea of moving the html package here is that it would not longer be maintained.

**Comment by 41eight** [comment]
@GrahamCampbell just out of curiosity, is there any specific reason that it is being dropped?

**Comment by GrahamCampbell** [comment]
It was taking too much time to maintain than what it was actually worth to anyone. Taylor made the decision that community maintained solutions were probably the way forward for the html and remote components.

**Comment by TimeToogo** [comment]
Any recommendations?

**Comment by GrahamCampbell** [comment]
My recommendation, is actually just write plain html code instead of messing about with other solutions. It's way more readable.

**Comment by TimeToogo** [comment]
Fair call

**Comment by onbjerg** [comment]
I'll just fork this then, if it's no longer being maintained. Thanks for your time.

**Comment by johnathanmdell** [comment]
Thanks for your time @taylorotwell @GrahamCampbell 

+1 @varghesejacob

**Pull request merged**
