### PR TITLE
Update HtmlServiceProvider.php

### PR DESCRIPTION
**Pull request by anaganisk**
modified bindshared() to singleton() , since bindshared() has been deprecated 
and to avoid the error
Script php artisan clear-compiled handling the post-install-cmd event returned with an error

### CODE REVIEW

**Comment by anaganisk** [comment]
@taylorotwell Please merge this since the facade is rendering the app useless when used without the edit.

**Comment by jstrength** [comment]
Just had to fix this myself, please fix.

**Comment by malyusha** [comment]
Had the same problem in Laravel 5.2.

**Comment by garygreen** [comment]
@taylorotwell It's such a simple change... please merge PR, pretty please ! @GrahamCampbell  can you ping Taylor if he's not watching this pls :smile:

**Comment by GrahamCampbell** [comment]
This will not be merged. Please close this.

**Comment by romaindrx** [comment]
Yes I've a same problem, and I fix with replace  "bindshared" to "singleton" {laravel:5.2}

**Comment by jsposato** [comment]
@GrahamCampbell why won't this be merged? It seems this package cannot be used with laravel 5.2 until it's updated.  Is there a replacement package?

**Comment by GrahamCampbell** [comment]
This package was not intended for use beyond laravel 4.2.

**Comment by jsposato** [comment]
Ok, seems this is the replacement: https://laravelcollective.com/docs/5.2/html

I must have missed the announcement, apologies.  :)

**Comment by anaganisk** [comment]
@GrahamCampbell just curious to know why Jeffrey Way was using it in that case on tutorials video for  Beginning with laravel 5 on Laracasts. Since Beginners like me just go on the wrong path ending up wasting time on a package the was deprecated. At least a mention about this in Readme would be nice :)

**Comment by garygreen** [comment]
tbh i dont see why this can't be merged.. It's a minor update to allow it be installed in 5.2, that is it. It's not exactly continuing development... Also @GrahamCampbell saying it's not intended beyond 4.2 is a bit misleading when Taylor updated it to support 5.

**Comment by GrahamCampbell** [comment]
No he didn't. It's only installable on 5.0.x, and that's it.

**Comment by GrahamCampbell** [comment]
The fact that it may work on later versions is simply coincidental, and was is not intended.

**Comment by garygreen** [comment]
So Taylor did [this commit](https://github.com/illuminate/html/commit/1076478696f786833a1b753be5097c2e82d36a6e) by accident? Seems _intended_ to me. Maybe that commit should be reversed then? Come on, this is just silly.

**Comment by garygreen** [comment]
I think it's also reasonable because it's only minor versions. Laravel 5.0 is supported, but not the minor versions 5.1, 5.2?

Doesn't bother me too much cos I've switched to Collective but I'm purely thinking about the newcomers to Laravel... I can see this being conflicting and confusing.

**Comment by GrahamCampbell** [comment]
> Laravel 5.0 is supported

5.x is NOT SUPPORTED. It was just "allowed" to give people time to find something else.

**Pull request closed without merging**
