### PR TITLE
Added all remaining html5 input type methods.

### PR DESCRIPTION
**Pull request by sebastiansulinski**
Added: color, date, datetime, datetime-local, time, week, month, number, range and tel methods.

### CODE REVIEW

**Comment by juizmill** [comment]
very good miss them ..

**Comment by mateusjatenee** [comment]
Thanks! :+1:

**Comment by GrahamCampbell** [comment]
Please close this.

**Comment by AndyWendt** [comment]
I don't think taylor is accepting additions.  I think you need to be looking at [LaravelCollective/html](https://github.com/LaravelCollective/html)

**Comment by GrahamCampbell** [comment]
Laravel Collective is not the official replacement just to be clear. There is no official replacement.

**Comment by sebastiansulinski** [comment]
Oh well - let's just close it then - shame, but will probably have to simply extend that one for my own purposes.

**Pull request closed without merging**
